#!/bin/bash
# Redis 一键安装脚本（适配 CentOS / Ubuntu，2G 内存优化）
# 用法: sudo bash scripts/setup_redis.sh [redis_password]

set -e

REDIS_PASSWORD="${1:-pt_redis_$(openssl rand -hex 8)}"

echo "====== Redis 安装脚本 ======"

# 检测包管理器
if command -v yum &>/dev/null; then
    PKG_MANAGER="yum"
    echo "检测到 CentOS/RHEL 系统"
elif command -v apt-get &>/dev/null; then
    PKG_MANAGER="apt-get"
    echo "检测到 Ubuntu/Debian 系统"
else
    echo "错误: 不支持的系统，请手动安装 Redis"
    exit 1
fi

# 检查是否已安装
if command -v redis-server &>/dev/null || command -v redis-cli &>/dev/null; then
    echo "Redis 已安装，跳过安装步骤"
else
    echo "正在安装 Redis..."
    if [ "$PKG_MANAGER" = "yum" ]; then
        yum install -y redis
    else
        apt-get update -qq
        apt-get install -y -qq redis-server
    fi
    echo "Redis 安装完成"
fi

# 查找配置文件
if [ -f /etc/redis.conf ]; then
    REDIS_CONF="/etc/redis.conf"
elif [ -f /etc/redis/redis.conf ]; then
    REDIS_CONF="/etc/redis/redis.conf"
else
    echo "错误: 找不到 Redis 配置文件"
    exit 1
fi

echo "配置文件: $REDIS_CONF"

# 备份原配置
cp "$REDIS_CONF" "${REDIS_CONF}.bak.$(date +%Y%m%d%H%M%S)"

# 写入 2G 内存优化配置
cat > "$REDIS_CONF" << CONF_EOF
# 2G 服务器优化配置 — generated by setup_redis.sh

bind 127.0.0.1
port 6379
requirepass $REDIS_PASSWORD

daemonize yes
pidfile /var/run/redis/redis-server.pid
logfile /var/log/redis/redis.log
dir /var/lib/redis

# 内存限制
maxmemory 128mb
maxmemory-policy allkeys-lru

# 持久化（AOF 保证重启不丢队列数据）
appendonly yes
appendfsync everysec

# 超时
timeout 300
tcp-keepalive 60
CONF_EOF

# 确保目录存在
mkdir -p /var/run/redis /var/log/redis /var/lib/redis
chown -R redis:redis /var/run/redis /var/log/redis /var/lib/redis

# 启动 Redis
if command -v systemctl &>/dev/null; then
    systemctl enable redis
    systemctl restart redis
    echo "Redis 已启动 (systemd)"
else
    redis-server "$REDIS_CONF"
    echo "Redis 已启动 (直接启动)"
fi

# 验证
sleep 1
if redis-cli -a "$REDIS_PASSWORD" ping 2>/dev/null | grep -q PONG; then
    echo ""
    echo "====== Redis 安装成功 ======"
    echo ""
    echo "连接信息:"
    echo "  REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0"
    echo ""
    echo "请将上面的 REDIS_URL 添加到 backend/.env 文件中"
else
    echo "警告: Redis 启动后 ping 检查失败，请手动检查"
fi
